version: '2.4'
services:
  db:
    image: mysql
    container_name: projetoSQL
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - projeto_sql:/var/lib/mysql

volumes:
  projeto_sql:
